Home_Shoppe/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Home_Shoppe.Models
{
    public class Bill
    {
        [Key]
        [StringLength(20)]
        public string IdBill { get; set; }

        [StringLength(20)]
        public string UserID { get; set; }

        public string ReceiverName { get; set; }

        public string Phone { get; set; }

        public string DiliveryAddress { get; set; }

        public string Note{ get; set; }

        public DateTime Time { get; set; }

        public int? TotalQuantity { get; set; }

        public string Status { get; set; }

        public double? TotalPayment { get; set; }


        public List<Cart> carts { get; set; }
    }
}

Home_Shoppe/Areas/Admin/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Home_Shoppe.Models;
using Microsoft.AspNet.Identity;

namespace Home_Shoppe.Areas.Admin.Controllers
{
    public class BillsController : Controller
    {
        private HomeShopDbContext db = new HomeShopDbContext();

        [Authorize(Roles = "Admin,Maganer,Employee")]
        // GET: Admin/Bills
        public ActionResult Index()
        {
            return View(db.Bills.ToList());
        }

        // GET: Admin/Bills/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.bill = bill;
            var carts = db.Carts.SqlQuery("Select * from Carts where IdBill='" + id + "'");
            ViewBag.TotalPrice = carts.Sum(x => x.Total);
            ViewBag.TotalQuantity = carts.Sum(x => x.Quantity);
            return View(carts.ToList());
        }

        

        

        // POST: Admin/Bills/index
        
        [HttpPost,ActionName("Index")]
        public ActionResult Edit(string idbill,string Status, string btn)
        {
            if (ModelState.IsValid)
            {
                Bill bill = db.Bills.Find(idbill);
                if (btn=="Update")
                {
                    bill.Status = Status;
                    db.Entry(bill).State = EntityState.Modified;
                }
                if(btn== "Delete")
                {
                    db.Bills.Remove(bill);
                    db.SaveChanges();
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Home_Shoppe/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Home_Shoppe.Models;
using Microsoft.AspNet.Identity;

namespace Home_Shoppe.Controllers
{
    public class BillsController : Controller
    {
        private HomeShopDbContext db = new HomeShopDbContext();

        

        

        // GET: Bills/Create
        public ActionResult Pay()
        {
            var carts = db.Carts.SqlQuery("Select * from Carts where UserID='" + User.Identity.GetUserName() + "' and IdBill IS NULL");
            ViewBag.TotalPrice = carts.Sum(x => x.Total);
            ViewBag.TotalQuantity = carts.Sum(x => x.Quantity);
            
            return View(carts.ToList());
        }

        // POST: Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Pay(string ReceiverName,string Phone,string DiliveryAddress,string Note,double TotalPayment,int TotalQuantity)
        {
            Bill bill = new Bill();
            if (ModelState.IsValid)
            {
                Random r = new Random();
                long count = db.Bills.LongCount();
                string id = "CR" + r.Next(10, 99) + count.ToString("0000");
                bill.IdBill = id;
                bill.UserID = User.Identity.GetUserName();
                bill.ReceiverName = ReceiverName;
                bill.Phone = Phone;
                bill.DiliveryAddress = DiliveryAddress;
                bill.Time = DateTime.Now;
                bill.Status = "Wait for confirmtion";
                bill.TotalPayment = TotalPayment;
                bill.TotalQuantity = TotalQuantity;
                bill.Note = Note;
                db.Bills.Add(bill);
                //var update =db.Database.ExecuteSqlCommand("UPDATE Carts SET IdBill = '" + id + "' WHERE UserID = '" + User.Identity.GetUserName() + "' and IdBill IS NULL");
                var carts = db.Carts.SqlQuery("Select * from Carts where UserID='" + User.Identity.GetUserName() + "' and IdBill IS NULL");
                foreach(var cart in carts)
                {
                    cart.IdBill = id;
                    db.Entry(cart).State = EntityState.Modified;
                }
                
                db.SaveChanges();
                return RedirectToAction("../Shop/index");
            }

            return View();
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Home_Shoppe/Controllers/ShopController.cs
using Home_Shoppe.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Home_Shoppe.Controllers
{
    public class ShopController : Controller
    {
        public HomeShopDbContext db = new HomeShopDbContext();

        // GET: Shop
        public ActionResult Index()
        {
            
            return View();
        }
        
        
        //GET : data
        public static IEnumerable<Category> ListCategories()
        {
            var dba= new HomeShopDbContext();
            var c = dba.Categories.SqlQuery("Select * from Category ");
            return c;
        }
        public static IEnumerable<Product> NewProduct()
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product Where QuantityInStock>0 ORDER BY IdProduct DESC");
            return c;
        }

        public static IEnumerable<Product> RelatedProduct(string id)
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product where QuantityInStock>0 and IdCategory='" + id + "'"+" ORDER BY Views DESC");
            return c;
        }

        public static IEnumerable<Product> FeatureProduct()
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product Where QuantityInStock>0 ORDER BY Views DESC");
            return c;
        }
        // GET:  all Product
        public ActionResult AllProduct(int page=1,int pagesize=12 )
        {
            var p = db.Products.SqlQuery("Select * from Product Where QuantityInStock>0 ").ToPagedList(page,pagesize);
            return View(p);
        }
        //GET: Data
        public ActionResult Category(string id,int page = 1, int pagesize = 12)
        {
            var p = db.Products.SqlQuery("Select * from Product where QuantityInStock>0 and IdCategory='" + id+"'").ToPagedList(page, pagesize);
            ViewBag.NameCategory = db.Categories.SingleOrDefault(a => a.IdCategory == id).NameCategory;
            return View(p);
        }

        // GET: Shop/Details/5
        public ActionResult Details(string id)
        {
            
            var view = db.Products.SingleOrDefault(a => a.IdProduct == id );
            
            return View(view);
        }
        
        [HttpPost]
       
        public ActionResult CreateCart(string IdProduct, double Price, string Color, int Quantity)
        {
            Cart cart = new Cart();
            if (ModelState.IsValid)
            {
                long count = db.Carts.LongCount();
                string id = "CART" + count.ToString("00000");
                cart.IdCart = "test123";
                cart.UserID = User.Identity.GetUserId();
                cart.IdProduct = "P00008";
                cart.Price = Price;
                cart.Quantity = 1;
                cart.Color = "blue";
                cart.Total = 4;
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        //GET: shop/search

        [HttpPost]
        public ActionResult Search(string Search, int page = 1, int pagesize = 8)
        {
            var products = db.Products.SqlQuery("Select * from Product Where QuantityInStock>0 ").ToPagedList(page, pagesize);
            //var resultList = products;
            //if (!String.IsNullOrEmpty(Search))
            // resultList = products.Where(t => t.NameProduct.Contains(Search)).ToPagedList(page, pagesize);
            ViewBag.keyword = Search;
            return View(products);

        }
        // GET: Shop/About
        public ActionResult About()
        {
            return View();
        }

        // GET: Shop/Delivery
        public ActionResult Delivery()
        {
            return View();
        }

        // GET: Shop/Contact
        public ActionResult Contact()
        {
            return View();
        }

        // GET: Shop/News
        public ActionResult News()
        {
            return View();
        }

        
    }
}

Home_Shoppe/Areas/Admin/Views/Bills/Details.cshtml
@model IEnumerable<Home_Shoppe.Models.Cart>

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<br />
<h2 style="text-align:center">Bill</h2>
<hr />

<div class="form-group">
    Receiver Name: @ViewBag.bill.ReceiverName

</div>
<div class="form-group">
    Phone : @ViewBag.bill.Phone

</div>
<div class="form-group">
    Dilivery Address : @ViewBag.bill.DiliveryAddress

</div>

<div class="form-group">
    Note : @ViewBag.bill.Note

</div>

<br />

<table width="80%" border="1">
    <thead>
        <tr>
            <td style=" font-weight:bold">Product</td>
            <td style=" font-weight:bold">Quantity</td>
            <td style=" font-weight:bold">Total</td>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>

                <td>@item.Product.NameProduct </td>
                <td>@item.Quantity</td>
                <td>@item.Total</td>
            </tr>

        </tbody>

    }
    <br />
    <tfoot>
        <tr>
            <td colspan="2" style="text-align:right; font-weight:bold;color:red;top:10px">Total:</td>
            <td style="text-align:left;top:10px">
                $@ViewBag.TotalPrice
                <input type="hidden" name="TotalPayment" value="@ViewBag.TotalPrice">
                <input type="hidden" name="TotalQuantity" value="@ViewBag.TotalQuantity">
            </td>
        </tr>
    </tfoot>
</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Home_Shoppe/Areas/Admin/Views/Bills/Index.cshtml
@model IEnumerable<Home_Shoppe.Models.Bill>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<style>

    .header__sort-bar {
        display: none;
    }

    table {
        width: 100%;
        font-size: 14px;
        margin-bottom: 32px;
    }

    th, td {
        min-width: 50px;
        padding: 8px;
    }

    .content-detail {
        text-decoration: none;
        color: blue;
    }

        .content-detail:hover {
            color: cornflowerblue;
        }

    .content-btn {
    }
</style>
<br />
<h2 style="text-align:center">Bill Management</h2>
<br />
<table align="center" border="1">
    <tr style="text-align:center; font-weight:bold; width: 80%;">
        <th> Id Bill</th>
        <th> User</th>
        <th>Receiver Name</th>
        <th> Status</th>
        <th>Total Quantity</th>
        <th> TotalPayment</th>
        <th> Time</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr style="text-align:center;font-weight:bold">
        @using (Html.BeginForm())
        {
            <td><a href="@Url.Action("Details", "Shop", new { id = item.IdBill })">@item.IdBill</a></td>
            <td> @item.UserID </td>
            <td> @item.ReceiverName </td>
            <td>
                <select name="Status" style="color:black">
                    @if (@item.Status == "Wait for confirmtion")
                    {
                        <option value="Wait for confirmtion" selected>Wait for confirmtion</option>
                        <option value="Preparing">Preparing</option>
                        <option value="Delivering">Delivering</option>
                        <option value="Delivered">Delivered</option>
                    }
                    @if (@item.Status == "Preparing")
                    {
                        <option value="Wait for confirmtion">Wait for confirmtion</option>
                        <option value="Preparing" selected>Preparing</option>
                        <option value="Delivering">Delivering</option>
                        <option value="Delivered">Delivered</option>
                    }
                    @if (@item.Status == "Delivering")
                    {
                        <option value="Wait for confirmtion">Wait for confirmtion</option>
                        <option value="Preparing">Preparing</option>
                        <option value="Delivering" selected>Delivering</option>
                        <option value="Delivered">Delivered</option>
                    }
                    @if (@item.Status == "Delivered")
                    {
                        <option value="Wait for confirmtion">Wait for confirmtion</option>
                        <option value="Preparing">Preparing</option>
                        <option value="Delivering">Delivering</option>
                        <option value="Delivered" selected>Delivered</option>
                    }

                </select>
                <input type="hidden" name="idbill" value="@item.IdBill" />
            </td>
            
            <td>@item.TotalQuantity</td>
            <td>@item.TotalPayment</td>
            <td>@item.Time</td>
            <td>
                <a href="@Url.Action("Details", "Bills", new { id = item.IdBill })" class="content-detail"> Details </a>
            </td>
            <td> <input type="submit" value="Update" name="btn" style="color:black" /></td>
            <td> <input type="submit" value="Delete" name="btn" style="color:black" /> </td>

        }
    </tr>

    }
</table>