Home_Shoppe/Models/Category.cs
namespace Home_Shoppe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Category")]
    public class Category
    {
        [Key]
        [StringLength(20)]
        public string IdCategory { get; set; }

        [Required(ErrorMessage = "NameCategory {0} is required")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "NameCategory")]
        [DataType(DataType.Text)]
        public string NameCategory { get; set; }


        public virtual ICollection<Product> Products { get; set; }
    }
}

Home_Shoppe/Models/Contact.cs
namespace Home_Shoppe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Contact")]
    public class Contact
    {
        [Key]
        [StringLength(20)]
        public string IdContect { get; set; }

        [StringLength(50)]
        public string name { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(50)]
        public string CompanyName { get; set; }

        [DataType(DataType.Text)]
        public string Subject { get; set; }
    }
}

Home_Shoppe/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Home_Shoppe.Models;
using PagedList;

namespace Home_Shoppe.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        

        private HomeShopDbContext db = new HomeShopDbContext();

        [Authorize(Roles = "Admin,Maganer,Employee")]

        // GET: Admin/Categories
        public ActionResult Index(int page = 1, int pagesize = 12)
        {
            var p = db.Categories.SqlQuery("Select * from Category ").ToPagedList(page, pagesize);
            return View(p);
        }

        // GET: Admin/Categories/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Admin/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCategory,NameCategory")] Category category)
        {
            Random r = new Random();
            long count = db.Categories.LongCount();
            string id = "C" +r.Next(10,99)+ count.ToString("00000");
            category.IdCategory = id;
            if (ModelState.IsValid)
            {

                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Admin/Categories/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCategory,NameCategory")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Admin/Categories/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Home_Shoppe/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Home_Shoppe.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Home_Shoppe.Controllers
{
    public class CartsController : Controller
    {
        private HomeShopDbContext db = new HomeShopDbContext();


        // GET: Carts
        public ActionResult Index()
        {
            var carts = db.Carts.SqlQuery("Select * from Carts where UserID='" + User.Identity.GetUserName() + "' and IdBill IS NULL");
            ViewBag.QuantityProduct = carts.Count();
            ViewBag.TotalPrice = carts.Sum(x => x.Total);
            return View(carts.ToList());
        }

        // POST: Carts/Index
        [HttpPost, ActionName("Index")]
        public ActionResult Index(string IdCart, string Color,int Quantity,string btn)
        {
            
            var cart = db.Carts.Find(IdCart);
            
            if (ModelState.IsValid)
            {
                if (btn == "Update")
                {
                    cart.Color = Color;
                    cart.Quantity = Quantity;
                    db.Entry(cart).State = EntityState.Modified;
                    db.SaveChanges();
                }
                if(btn == "Delete")
                {
                    db.Carts.Remove(cart);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: Carts/Create
        [HttpPost]
        public ActionResult Create(string IdProduct, double Price, string Color, int Quantity)
        {
            Cart cart = new Cart();
            if (ModelState.IsValid)
            {
                Random r = new Random();
                long count = db.Carts.LongCount();
                string id = "CR" +r.Next(10,99)+ count.ToString("0000");
                cart.IdCart = id;
                cart.UserID = User.Identity.GetUserName();
                cart.IdProduct = IdProduct;
                cart.Price = Price;
                cart.Quantity = Quantity;
                cart.Color = Color;
                cart.Total = 4;
                db.Carts.Add(cart);
                db.SaveChanges(); 
                return RedirectToAction("../Shop/index");
            }

            ViewBag.IdProduct = new SelectList(db.Products, "IdProduct", "IdCategory", cart.IdProduct);
            return View(cart);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Home_Shoppe/Controllers/ShopController.cs
using Home_Shoppe.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Home_Shoppe.Controllers
{
    public class ShopController : Controller
    {
        public HomeShopDbContext db = new HomeShopDbContext();

        // GET: Shop
        public ActionResult Index()
        {
            
            return View();
        }
        
        
        //GET : data
        public static IEnumerable<Category> ListCategories()
        {
            var dba= new HomeShopDbContext();
            var c = dba.Categories.SqlQuery("Select * from Category ");
            return c;
        }
        public static IEnumerable<Product> NewProduct()
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product Where QuantityInStock>0 ORDER BY IdProduct DESC");
            return c;
        }

        public static IEnumerable<Product> RelatedProduct(string id)
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product where QuantityInStock>0 and IdCategory='" + id + "'"+" ORDER BY Views DESC");
            return c;
        }

        public static IEnumerable<Product> FeatureProduct()
        {
            var dba = new HomeShopDbContext();
            var c = dba.Products.SqlQuery("Select TOP(4) * from Product Where QuantityInStock>0 ORDER BY Views DESC");
            return c;
        }
        // GET:  all Product
        public ActionResult AllProduct(int page=1,int pagesize=12 )
        {
            var p = db.Products.SqlQuery("Select * from Product Where QuantityInStock>0 ").ToPagedList(page,pagesize);
            return View(p);
        }
        //GET: Data
        public ActionResult Category(string id,int page = 1, int pagesize = 12)
        {
            var p = db.Products.SqlQuery("Select * from Product where QuantityInStock>0 and IdCategory='" + id+"'").ToPagedList(page, pagesize);
            ViewBag.NameCategory = db.Categories.SingleOrDefault(a => a.IdCategory == id).NameCategory;
            return View(p);
        }

        // GET: Shop/Details/5
        public ActionResult Details(string id)
        {
            
            var view = db.Products.SingleOrDefault(a => a.IdProduct == id );
            
            return View(view);
        }
        
        [HttpPost]
       
        public ActionResult CreateCart(string IdProduct, double Price, string Color, int Quantity)
        {
            Cart cart = new Cart();
            if (ModelState.IsValid)
            {
                long count = db.Carts.LongCount();
                string id = "CART" + count.ToString("00000");
                cart.IdCart = "test123";
                cart.UserID = User.Identity.GetUserId();
                cart.IdProduct = "P00008";
                cart.Price = Price;
                cart.Quantity = 1;
                cart.Color = "blue";
                cart.Total = 4;
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        //GET: shop/search

        [HttpPost]
        public ActionResult Search(string Search, int page = 1, int pagesize = 8)
        {
            var products = db.Products.SqlQuery("Select * from Product Where QuantityInStock>0 ").ToPagedList(page, pagesize);
            //var resultList = products;
            //if (!String.IsNullOrEmpty(Search))
            // resultList = products.Where(t => t.NameProduct.Contains(Search)).ToPagedList(page, pagesize);
            ViewBag.keyword = Search;
            return View(products);

        }
        // GET: Shop/About
        public ActionResult About()
        {
            return View();
        }

        // GET: Shop/Delivery
        public ActionResult Delivery()
        {
            return View();
        }

        // GET: Shop/Contact
        public ActionResult Contact()
        {
            return View();
        }

        // GET: Shop/News
        public ActionResult News()
        {
            return View();
        }

        
    }
}

Home_Shoppe/Views/Shop/AllProduct.cshtml
@model PagedList.IPagedList<Home_Shoppe.Models.Product>
@using PagedList.Mvc;
@{
    ViewBag.Title = "AllProduct";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="header_slide">
    <div class="header_bottom_left">
        @Html.Partial("_Categories", Home_Shoppe.Controllers.ShopController.ListCategories())
    </div>
    <div class="header_bottom_right">
        <div class="slider">
            <div id="slider">
                <div id="mover">
                    <div id="slide-1" class="slide">
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Asset/images/slide-1-image.png" alt="learn more" /></a>
                        </div>
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 20% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="slide">
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 40% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Asset/images/slide-3-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="slide">
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Asset/images/slide-2-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 10% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="main">
    <div class="content">
        <div class="content_top">
            <div class="heading">
                <h3>All Products</h3>
            </div>

            <div class="clear"></div>
        </div>
        <div class="section group">
            @foreach (var item in Model)
            {

                <div class="grid_1_of_4 images_1_of_4">
                    <a href="@Url.Action("Details", "Shop", new { id = item.IdProduct })"><img src="~/Asset/data/@item.Image1" alt="" style="width:212px;height:212px;" /></a>
                    <h2>@item.NameProduct </h2>
                    <div class="price-details">
                        <div class="price-number">
                            <p><span class="rupees">@item.Price $</span></p>
                        </div>
                        <div class="add-cart">
                            <h4><a href="@Url.Action("Details", "Shop", new { id = item.IdProduct })">Add to Cart</a></h4>
                        </div>
                        <div class="clear"></div>
                    </div>

                </div>
            }
        </div>
        <div class="content-pagenation">
            @Html.PagedListPager(Model, page => Url.Action("AllProduct",
                new { page }))
        </div>
    </div>

Home_Shoppe/Views/Shop/Details.cshtml
@model Home_Shoppe.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="main">
    <div class="content">
        <div class="content_top">
            <div class="back-links">
                <p><a href="@Url.Action("Index", "Shop")">Home</a> >>>> <a href="@Url.Action("Category", "Shop", new { id = Model.Category.IdCategory })">@Model.Category.NameCategory</a></p>
            </div>
            <div class="clear"></div>
        </div>


        <div class="section group">
            <div class="cont-desc span_1_of_2">
                <div class="product-details">
                    <div class="grid images_3_of_2">
                        <div id="container">
                            <div id="products_example">
                                <div id="products">
                                    <div class="slides_container">
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image1" alt=" " style="width:366px;height:275px;" /></a>
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image2" alt=" " style="width:366px;height:275px;" /></a>
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image3" alt=" " style="width:366px;height:275px;" /></a>
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image4" alt=" " style="width:366px;height:275px;" /></a>
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image5" alt=" " style="width:366px;height:275px;" /></a>
                                        <a href="#" target="_blank"><img src="~/Asset/data/@Model.Image6" alt=" " style="width:366px;height:275px;" /></a>
                                    </div>
                                    <ul class="pagination">
                                        <li><a href="#"><img src="~/Asset/data/" alt=" " /></a></li>
                                        <li><a href="#"><img src="~/Asset/data/@Model.Image2" alt=" " /></a></li>
                                        <li><a href="#"><img src="~/Asset/data/@Model.Image3" alt=" " /></a></li>
                                        <li><a href="#"><img src="~/Asset/data/@Model.Image4" alt=" " /></a></li>
                                        <li><a href="#"><img src="~/Asset/data/@Model.Image5" alt=" " /></a></li>
                                        <li><a href="#"><img src="~/Asset/data/@Model.Image6" alt=" " /></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    @using (Html.BeginForm("Create", "Carts", FormMethod.Post))
                    {

                        <div class="desc span_3_of_2">
                            <h2>@Model.NameProduct </h2>
                            <p>@Model.Description</p>
                            <div class="price">
                                <p>Price: <span>$@Model.Price</span></p>
                            </div>
                            <div class="available">
                                <p>Available Options :</p>
                                <ul>
                                    <li>
                                        Color:
                                        <select name="Color">
                                            <option value="Silver">Silver</option>
                                            <option value="Black">Black</option>
                                            <option value="Dark">Dark</option>
                                            <option value="Red">Red</option>
                                        </select>
                                    </li>

                                    <li>
                                        Quality:<input class="form-inline quantity" type="number" value="1" min="1" max="@Model.QuantityInStock" name="Quantity" />
                                    </li>
                                </ul>
                            </div>
                            <div class="share-desc">
                                <div class="share">
                                    <p>Share Product :</p>
                                    <ul>
                                        <li><a href="#"><img src="~/Asset/images/facebook.png" alt="" /></a></li>
                                        <li><a href="#"><img src="~/Asset/images/twitter.png" alt="" /></a></li>
                                    </ul>
                                </div>

                                <input type="hidden" name="IdProduct" value="@Model.IdProduct" />
                                <input type="hidden" name="Price" value="@Model.Price" />

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <input type="submit" value="Add to Cart" class="button">
                                }
                                else
                                {
                                    @Html.ActionLink("Add to Cart", "Login", "Account", null, htmlAttributes: new { @class = "button" })
                                }
                                <div class="clear"></div>
                            </div>
                            <div class="wish-list">
                                <ul>
                                    <li class="wish"><a href="#">Add to Wishlist</a></li>
                                    <li class="compare"><a href="#">Add to Compare</a></li>
                                </ul>
                            </div>
                        </div>
                    }
                    <div class="clear"></div>
                </div>
                <div class="product_desc">
                    <div id="horizontalTab">
                        <ul class="resp-tabs-list">
                            <li>Product Details</li>
                            <li>product Tags</li>
                            <li>Product Reviews</li>
                            <div class="clear"></div>
                        </ul>
                        <div class="resp-tabs-container">
                            <div class="product-desc">
                                <p>@Model.ProductDetails</p>

                            </div>

                            <div class="product-tags">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                                <h4>Add Your Tags:</h4>
                                <div class="input-box">
                                    <input type="text" value="">
                                </div>
                                <div class="button"><span><a href="#">Add Tags</a></span></div>
                            </div>

                            <div class="review">
                                <h4>Lorem ipsum Review by <a href="#">Finibus Bonorum</a></h4>
                                <ul>
                                    <li>Price :<a href="#"><img src="~/Asset/images/price-rating.png" alt="" /></a></li>
                                    <li>Value :<a href="#"><img src="~/Asset/images/value-rating.png" alt="" /></a></li>
                                    <li>Quality :<a href="#"><img src="~/Asset/images/quality-rating.png" alt="" /></a></li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                                <div class="your-review">
                                    <h3>How Do You Rate This Product?</h3>
                                    <p>Write Your Own Review?</p>
                                    <form>
                                        <div>
                                            <span><label>Nickname<span class="red">*</span></label></span>
                                            <span><input type="text" value=""></span>
                                        </div>
                                        <div>
                                            <span><label>Summary of Your Review<span class="red">*</span></label></span>
                                            <span><input type="text" value=""></span>
                                        </div>
                                        <div>
                                            <span><label>Review<span class="red">*</span></label></span>
                                            <span><textarea> </textarea></span>
                                        </div>
                                        <div>
                                            <span><input type="submit" value="SUBMIT REVIEW"></span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('#horizontalTab').easyResponsiveTabs({
                            type: 'default', //Types: default, vertical, accordion
                            width: 'auto', //auto or any width like 600px
                            fit: true   // 100% fit in a container
                        });
                    });
                </script>
                <div class="content_bottom">
                    <div class="heading">
                        <h3>Related Products</h3>
                    </div>
                    <div class="see">
                        <p><a href="@Url.Action("Category", "Shop", new { id = Model.Category.IdCategory  })">See all Products</a></p>
                    </div>
                    <div class="clear"></div>
                </div>
                @Html.Partial("_Top4Product", Home_Shoppe.Controllers.ShopController.RelatedProduct(Model.Category.IdCategory))
            </div>
            <div class="rightsidebar span_3_of_1">
                <h2>CATEGORIES</h2>
                <ul class="side-w3ls">
                    @Html.Partial("_Categories", Home_Shoppe.Controllers.ShopController.ListCategories())
                </ul>
                <div class="subscribe">
                    <h2>Newsletters Signup</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.......</p>
                    <div class="signup">
                        <form>
                            <input type="text" value="E-mail address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'E-mail address';"><input type="submit" value="Sign up">
                        </form>
                    </div>
                </div>
                <div class="community-poll">
                    <h2>Community POll</h2>
                    <p>What is the main reason for you to purchase products online?</p>
                    <div class="poll">
                        <form>
                            <ul>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="1">
                                    <span class="label"><label>More convenient shipping and delivery </label></span>
                                </li>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="2">
                                    <span class="label"><label for="vote_2">Lower price</label></span>
                                </li>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="3">
                                    <span class="label"><label for="vote_3">Bigger choice</label></span>
                                </li>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="5">
                                    <span class="label"><label for="vote_5">Payments security </label></span>
                                </li>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="6">
                                    <span class="label"><label for="vote_6">30-day Money Back Guarantee </label></span>
                                </li>
                                <li>
                                    <input type="radio" name="vote" class="radio" value="7">
                                    <span class="label"><label for="vote_7">Other.</label></span>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Home_Shoppe/Views/Shop/_Categories.cshtml
@model IEnumerable<Home_Shoppe.Models.Category>
    <div class="categories">
        <ul>
            <h3>Categories</h3>
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("Category", "Shop", new { id = item.IdCategory })">@item.NameCategory</a></li>
            }
        </ul>
    </div>